apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    app: widgetario
spec:
  ports:
    - port: 5432
      targetPort: postgres # Directs traffic to the PostgreSQL database port
  selector:
    app: widgetario
    component: products-db
  type: ClusterIP
  clusterIP: None # Headless service to enable direct pod-to-pod communication