apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    app: widgetario
spec:
  ports:
    - port: 80
      targetPort: http # Routes traffic to the container's HTTP port
  selector:
    app: widgetario
    component: products-api
  type: ClusterIP # Internal service, exposes only within the cluster