apiVersion: v1
kind: Secret
metadata:
  name: web-api
type: Opaque
stringData:
 # Contains API endpoint URLs for internal Widgetario services
  api.json: |-
    {
      "Widgetario": {
        "ProductsApi": {
          "Url": "http://products-api.default.svc.cluster.local/products"
        },
        "StockApi": {
          "Url": "http://stock-api.default.svc.cluster.local/stock"
        }
      }
    }