apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
type: Opaque
stringData:
# Database connection string for the stock API, includes host, port, user, and password
  POSTGRES_CONNECTION_STRING: "host=products-db-1.products-db.default.svc.cluster.local port=5432 user=postgres password=h4ckkath0n dbname=postgres sslmode=disable"