apiVersion: v1
kind: Secret
metadata:
  name: products-db-password
type: Opaque
stringData:
# Password credentials for PostgreSQL database access
  POSTGRES_PASSWORD: h4ckkath0n
  PGPASSWORD: h4ckkath0n