apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    app: widgetario
spec:
  selector:
    matchLabels:
        app: widgetario
        component: stock-api
  template:
    metadata:
      labels: 
        app: widgetario
        component: stock-api
        hackathon: part-1
    spec:
      containers:
        - name: app
          image: widgetario/stock-api:21.03
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: stock-api-connection
          volumeMounts:
            - name: cache
              mountPath: "/cache" # Temporary storage for caching within the container
      volumes:
        - name: cache
          emptyDir: {} # Ephemeral volume that lasts only as long as the pod is running