apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-lb
  labels:
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:  
    app: widgetario
    component: web
  type: LoadBalancer # Exposes service externally with a cloud provider's load balancer
---
apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-np
  labels:
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30008 # Fixed node port for external access on each node
  selector:
    app: widgetario
    component: web
  type: NodePort # Exposes service on a static port on each cluster node for external access