apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.2.0 # Ingress controller image version
          args:
            - /nginx-ingress-controller
            - --publish-service=ingress-nginx/ingress-nginx-controller-lb # External LB service
            - --publish-service=ingress-nginx/ingress-nginx-controller-np # NodePort service
            - --election-id=ingress-controller-leader  # Leader election for HA
            - --ingress-class=nginx   # Defines the ingress class used for routing         
            - --controller-class=k8s.io/ingress-nginx  # Explicit controller class
            - --configmap=ingress-nginx/ingress-nginx-controller # Links to configmap for custom settings
          securityContext:
            runAsUser: 101
            allowPrivilegeEscalation: true # Required for NGINX to bind to low ports
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
      serviceAccountName: ingress-nginx # Binds the DaemonSet to the correct service account with RBAC
